version: '3'

services:
    web:
        image: nginx:1.13.7
        ports:
            - "8000:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - texture
    texture:
        build:
            context: ./demo
            dockerfile: Dockerfile
            args:
                dependencies_sciencebeam: "${SCIENCEBEAM_TAG}"
        image: elifesciences/sciencebeam_texture:${IMAGE_TAG}
        command: npm run start:prod
        ports:
            - "4000:4000"
        depends_on:
            - sciencebeam
    sciencebeam:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --pipeline grobid \
            --grobid-url http://grobid:8070/api
        environment:
            - SCIENCEBEAM__XSLT_TEMPLATE_PARAMETERS__ACKNOWLEDGEMENT_TARGET=body
            - SCIENCEBEAM__XSLT_TEMPLATE_PARAMETERS__ANNEX_TARGET=body
        ports:
            - "8075:8075"
        networks:
            - default
            - grobid
        depends_on:
            - grobid
    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
        ports:
            - "8070:8070"
        networks:
            - grobid
    sciencebeam_biorxiv:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8076 \
            --pipeline grobid \
            --grobid-url http://grobid_biorxiv:8070/api
        environment:
            - SCIENCEBEAM__XSLT_TEMPLATE_PARAMETERS__ACKNOWLEDGEMENT_TARGET=body
            - SCIENCEBEAM__XSLT_TEMPLATE_PARAMETERS__ANNEX_TARGET=body
        ports:
            - "8076:8076"
        networks:
            - default
            - grobid
        depends_on:
            - grobid_biorxiv
    grobid_biorxiv:
        image: ${SCIENCEBEAM_GROBID_BIORXIV_REPO}:${SCIENCEBEAM_GROBID_BIORXIV_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
            - GROBID__HEADER__USE_LABELED_ABSTRACT=false
        ports:
            - "8072:8070"
        networks:
            - grobid

networks:
    default:
        internal: false
    grobid:
        internal: true
