version: '3'

services:
    web:
        image: nginx:1.13.7
        ports:
            - "8000:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - texture
    texture:
        build:
            context: ./demo
            dockerfile: Dockerfile
            args:
                dependencies_sciencebeam: "${SCIENCEBEAM_TAG}"
        image: elifesciences/sciencebeam_texture:${IMAGE_TAG}
        command: npm run start:prod
        ports:
            - "4000:4000"
        depends_on:
            - sciencebeam
    sciencebeam:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --pipeline grobid,sciencebeam_autocut \
            --grobid-url http://grobid:8070/api \
            --sciencebeam-autocut-url http://sciencebeam-autocut:8080/api/autocut \
            --sciencebeam-autocut-xpath front/article-meta/title-group/article-title
        ports:
            - "8075:8075"
        networks:
            - default
            - grobid
        depends_on:
            - sciencebeam-autocut
            - grobid
            - grobid-warmup
    sciencebeam-autocut:
        image: ${SCIENCEBEAM_AUTOCUT_REPO}:${SCIENCEBEAM_AUTOCUT_TAG}
        ports:
            - "8079:8080"
    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
        ports:
            - "8070:8070"
        networks:
            - grobid
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8070"]
            interval: 10s
            timeout: 10s
            retries: 5
    grobid-warmup:
        image: willwill/wait-for-it
        command: grobid:8070 -- /bin/sh -c "curl -v --form input=@/tmp/warmup-sample.pdf --form consolidateHeader=0 --form consolidateCitations=0 -o /dev/null http://grobid:8070/api/processFulltextDocument"
        volumes:
            - ./data/warmup-sample.pdf:/tmp/warmup-sample.pdf
        networks:
            - grobid
        depends_on:
            - grobid

networks:
    default:
        internal: false
    grobid:
        internal: true
