FROM node:9.8.0-stretch AS texture

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

ENV HOME=/home/dev-user
RUN mkdir ${HOME} && chown ${UNAME}:${GID} ${HOME}
USER ${UNAME}

ENV PROJECT_FOLDER=/opt/sciencebeam-texture
WORKDIR ${PROJECT_FOLDER}
