version: '3'

services:
    texture-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                USERNAME: ${USERNAME}
                UID: ${UID}
                GID: ${GID}
        image: elifesciences/sciencebeam_texture_dev:${IMAGE_TAG}
        command: npm run start
        ports:
            - "${TEXTURE_PORT_DEV}:8080"
